# Generated by Django 4.1.3 on 2022-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.BooleanField(choices=[(False, 'administrator'), (True, 'super_administrator')], default=True, verbose_name='Rol'),
        ),
    ]
