# Generated by Django 4.1.3 on 2022-11-13 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("password", models.CharField(max_length=30, verbose_name="password")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de creacion",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultima modificacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrator",
                "verbose_name_plural": "Administrators",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "paternal_surname",
                    models.CharField(max_length=200, verbose_name="paternal surname"),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="email")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultima modificacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PaymentCustomer",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="amount"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="product name"),
                ),
                ("quantity", models.IntegerField(verbose_name="quantity")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de creacion",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ultima modificacion"
                    ),
                ),
                (
                    "folio_boleto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="get_customer",
                        to="customer.customer",
                        verbose_name="customer id",
                    ),
                ),
            ],
            options={
                "verbose_name": "PaymentCustomer",
                "verbose_name_plural": "PaymentCustomers",
                "ordering": ["-created"],
            },
        ),
    ]
