# Generated by Django 4.1.3 on 2022-11-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentcustomer",
            name="folio_boleto",
        ),
    ]
