# Generated by Django 4.1.3 on 2022-11-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_remove_paymentcustomer_folio_boleto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
    ]
