# Generated by Django 4.1.3 on 2022-11-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='rol',
            field=models.CharField(choices=[('administrator', 'administrator'), ('super_administrator', 'super_administrator')], default='administrator', max_length=50, verbose_name='Rol'),
        ),
    ]
