# Generated by Django 4.1.3 on 2022-11-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_administrator_id_alter_paymentcustomer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
