# Generated by Django 4.1.3 on 2022-11-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='rol',
            field=models.BooleanField(choices=[(False, 'administrator'), (True, 'super_administrator')], default=True, verbose_name='Rol'),
        ),
    ]
